import type { Metadata } from "next";
import { getDictionary } from "@/lib/dictionary";
import { Locale } from "@/i18n.config";
import { cookies } from "next/headers";
import { AppSidebar } from "@/components/dashboard/sidebar/app-sidebar";
import { ModeSwitcher } from "@/components/mode-switcher";
import { NavHeader } from "@/components/nav-header";
import { Separator } from "@/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import LocaleSwitcher from "@/components/locale-switcher";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <SidebarProvider
      defaultOpen={defaultOpen}
      className="flex flex-col pt-(--header-height) [--header-height:calc(--spacing(14))]"
    >
      <header className="bg-background fixed inset-x-0 top-0 isolate z-10 flex shrink-0 items-center gap-2 border-b">
        <div className="flex h-(--header-height) w-full items-center gap-2 px-4">
          <SidebarTrigger className="-ml-1.5" />
          <Separator
            orientation="vertical"
            className="mr-2 data-[orientation=vertical]:h-4"
          />
          <NavHeader />
          <div className="ml-auto flex items-center gap-2">
            <ModeSwitcher />
            <LocaleSwitcher />
          </div>
        </div>
      </header>
      <div className="flex flex-1">
        <AppSidebar />
        <SidebarInset>{children}</SidebarInset>
      </div>
    </SidebarProvider>
  );
}
